version: '3.8'

services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: prod.Dockerfile
    restart: always
    environment:
      - NODE_ENV=production
      - NEXTAUTH_SECRET=UG4S6yE6JFeIbx2D3j+YAy9bV9QieOiPo7b5OytKj/8=
      - GOOGLE_ID=975762826109-46h48jp2c66fsn84pi854quf3l5otlgo.apps.googleusercontent.com
      - GOOGLE_SECRET=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
      - FACEBOOK_ID=969848614123456
      - FACEBOOK_SECRET=f34ac9bc652a3a768d449108a511d41d
      - GITHUB_ID=765d28dd6ff3d0b91d23
      - GITHUB_SECRET=69164a8d5e072bbbb1765965e8e8b49731533606
      - NEXT_PUBLIC_S3_CREDENTIAL_SECRET_ACCESS_KEY=A1HHCz6WMlmYUxj5VJnaAexvFH1tSg77eRA6V3MK
      - NEXT_PUBLIC_S3_CREDENTIAL_ACCESS_KEY_ID=AKIA5UVJCAVTE7AV35HL
      - NEXT_PUBLIC_S3_BUCKET_NAME=heartchat-repo
      - NEXT_PUBLIC_S3_IMAGE_URL=https://heartchat-repo.s3.eu-west-2.amazonaws.com/images/
    ports:
      - 3000:3000
    networks:
      - my_network
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    environment:
      - NODE_ENV=production
      - PGHOST=ep-broken-butterfly-78342458.eu-central-1.aws.neon.tech
      - PGDATABASE=neondb
      - PGUSER=viboloveyou12
      - PGPASSWORD=C9dju0TDOVpM
      - ENDPOINT_ID=ep-broken-butterfly-78342458
    ports:
      - "8000:8000"
    networks:
      - my_network

  # Add more containers below (nginx, postgres, etc.)

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  my_network:
    # external: true
    driver: bridge